name = 'xl_tables'
version = '1.0.2'
description = 'Read and write excel files using table descriptors.'
url = 'https://github.com/justengel/xl_tables'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
